run:
	LD_PRELOAD=/home.local/zyuxuan/floar/rca-clang/target/debug/librca.so /bin/sh -c "./main"

run-make:
	LD_PRELOAD=/home.local/zyuxuan/floar/rca-clang-server-client/target/debug/librca.so /bin/sh -c "/home.local/zyuxuan/clang/llvm-project/build/bin/clang main.c -o main"

